import * as THREE from 'three'
import { mesh } from './primitives'
const named=name=>{const g=new THREE.Group();g.name=name;return g}
const jaggedCone=(radius,height,segments,seed)=>{const geometry=new THREE.ConeGeometry(radius,height,segments,5);const positions=geometry.attributes.position;for(let i=0;i<positions.count;i++){const y=positions.getY(i),factor=1+(Math.sin(i*12.73+seed)*.11)*(1-Math.abs(y)/(height*.55));positions.setX(i,positions.getX(i)*factor);positions.setZ(i,positions.getZ(i)*(2-factor*.82))}geometry.computeVertexNormals();return geometry}
const peak=(m,x,z,s=1)=>{const g=new THREE.Group();g.add(mesh(jaggedCone(3.5*s,8*s,9,x+z),new THREE.MeshStandardMaterial({color:'#425066',roughness:.88}),[0,4*s,0]),mesh(jaggedCone(1.8*s,3.3*s,9,x-z),m.snow,[0,7.1*s,0]));g.position.set(x,0,z);return g}
export function createIceWorld(m,quality='desktop'){
  const world=new THREE.Group();world.name='ice-world';world.add(mesh(new THREE.PlaneGeometry(48,52,18,18),new THREE.MeshStandardMaterial({color:'#dce8ec',roughness:.78}),[0,-.15,0],[-Math.PI/2,0,0]))
  const fg=named('ice-foreground'),mid=named('ice-midground'),back=named('ice-background');for(let i=0;i<(quality==='mobile'?7:15);i++){const layer=i<4?fg:i<10?mid:back,z=-4-Math.floor(i/5)*10,x=(i%5-2)*6.3,s=.65+(i%4)*.14;layer.add(peak(m,x,z,s))}world.add(fg,mid,back)
  const glacier=named('glacier'),ice=new THREE.MeshPhysicalMaterial({color:'#83cddd',roughness:.16,transmission:.18,transparent:true,opacity:.86});glacier.add(mesh(new THREE.PlaneGeometry(15,34,6,16),ice,[4,.02,1],[-Math.PI/2,0,.16]));for(let i=0;i<7;i++)glacier.add(mesh(new THREE.BoxGeometry(.08,.03,3+(i%3)),m.dark,[1+i*1.1,.05,-13+i*4],[0,i*.12,0]));world.add(glacier)
  const trail=named('trek-path'),points=[];for(let i=0;i<18;i++)points.push(new THREE.Vector3(-5+Math.sin(i*.55)*2,.05,15-i*2));const curve=new THREE.CatmullRomCurve3(points);trail.add(mesh(new THREE.TubeGeometry(curve,100,.32,7,false),new THREE.MeshStandardMaterial({color:'#9aa9ac',roughness:1})));world.add(trail)
  const camp=named('base-camp');camp.position.set(-7,0,-10);[-1.2,1.2].forEach(x=>camp.add(mesh(new THREE.ConeGeometry(1.25,1.5,4),x<0?m.gold:m.sand,[x,.75,0],[0,Math.PI/4,0])));camp.add(mesh(new THREE.CylinderGeometry(.05,.06,2.2,8),m.wood,[0,1.1,0]),mesh(new THREE.BoxGeometry(2.8,1.3,.1),m.dark,[0,1.3,0]));world.add(camp)
  const snow=named('drifting-snow'),count=quality==='mobile'?160:520,positions=new Float32Array(count*3);for(let i=0;i<count;i++){positions[i*3]=(Math.random()-.5)*42;positions[i*3+1]=Math.random()*14;positions[i*3+2]=(Math.random()-.5)*45}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));snow.add(new THREE.Points(geo,new THREE.PointsMaterial({color:'#ffffff',size:.07,transparent:true,opacity:.7})));world.add(snow)
  const shelter=named('contact-shelter');shelter.position.set(5,0,-18);shelter.add(mesh(new THREE.BoxGeometry(6,2.6,3.5),m.wood,[0,1.3,0]),mesh(new THREE.ConeGeometry(4.2,2,4),m.snow,[0,3.2,0],[0,Math.PI/4,0]),mesh(new THREE.BoxGeometry(3,1.4,.08),ice,[0,1.5,1.76]));world.add(shelter)
  world.userData={route:curve,snow,copyAnchor:new THREE.Vector3(-7,2.2,-10)};const cold=new THREE.DirectionalLight('#b7d9ff',4);cold.position.set(-8,14,5);world.add(cold);return world
}
export function updateIceWorld(world,elapsed){if(world.userData.snow){world.userData.snow.rotation.y=elapsed*.015;world.userData.snow.position.y=Math.sin(elapsed*.4)*.15}}
